javascript-tutorial/ko.javascript.info

1-js/08-error-handling/1-try-catch/article.md

Error handling, "try..catch" Summary 장(끝)까지 번역하였습니다.

Error handling, "try..catch" Summary 장까지 번역

---

1-js/10-error-handling/2-custom-errors/article.md

10-error-handling > 2-custom-errors 번역 Pull 요청합니다

---

1-js/06-advanced-functions/07-new-function/article.md

#46 Re-Commit

---

1-js/06-advanced-functions/10-bind/article.md

#37 Re-Commit

---

2-ui/1-document/02-dom-nodes/article.md

이슈 #62 block에 대한 번역어 통일
블럭 > 블록 으로 변경.
First Commit 을 해보았습니다

2-ui/1-document/02-dom-nodes/article.md 블럭 번역어 통일

---

1-js/03-code-quality/01-debugging-chrome/article.md

두 군데 오탈자 수정한 부분입니다.
계속해서 다시 읽어 찾아보도록 하겠습니다.

1-js/03-code-quality/01-debugging-chrome/article.md 리뷰

---

1-js/01-getting-started/3-code-editors/article.md

1-js\01-getting-started\3-code-editors 2차 리뷰

---

1-js/05-data-types/05-array-methods/5-copy-sort-array/task.md

#174 Copy and sort array 과제 번역

---

1-js/05-data-types/03-string/3-truncate/task.md

#172 Truncate the text 과제 번역

---

1-js/99-js-misc/02-eval/1-eval-calculator/task.md

eval/task.md 수정사항 반영하였습니다. 리뷰 부탁드립니다.

eval 과제 번역 및 수정사항 반영

---

1-js/02-first-steps/01-hello-world/2-hello-alert-ext/solution.md

1-js/02-first-steps/01-hello-world/2-hello-alert-ext/solution.md 오타 수정

---

1-js/07-object-properties/01-property-descriptors/article.md

안녕하세요 Property descriptor 문서를 한번 살펴봤습니다. 리뷰 부탁드릴게요. 감사합니다.

Property descriptor 1차 리뷰

---

1-js/99-js-misc/02-eval/1-eval-calculator/solution.md

eval/solution.md 수정사항 반영해서 다시 번역했습니다. 리뷰 부탁드립니다.

eval 해답 번역 및 수정사항 반영

---

1-js/99-js-misc/02-eval/article.md

eval 번역 및 수정

---

1-js/08-prototypes/04-prototype-methods/article.md

안녕하세요?
해당 문서의 초벌 번역을 해봤습니다. 몇가지 어색한 표현이나 매끄럽지 않은 부분이 있으나 혼자선 좋은 생각이 나질 않네요. 리뷰 부탁드립니다 :)

 1-js / 08-prototypes / 04-prototype-methods 초벌 번역

---

2-ui/4-forms-controls/1-form-elements/1-add-select-option/solution.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[form-elements/add-select-option] 과제 해답 번역

---

2-ui/4-forms-controls/1-form-elements/1-add-select-option/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[Form properties and methods] 과제 번역

---

6-data-storage/02-localstorage/1-form-autosave/task.md
6-data-storage/02-localstorage/article.md

_6-data-storage/02-localstorage/article.md_
`origin` 번역을 고민하고 있습니다. `원본`이나 `출처`는 딱 들어맞지 않는 것 같아서요. 적합한 단어가 생각나시면 의견 부탁드립니다.

6-data-storage/02-localstorage/article.md 번역

---

1-js/09-classes/06-instanceof/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
감사합니다!

1-js/09-classes/06-instanceof 번역 완료

---

1-js/07-object-properties/02-property-accessors/article.md

링크해주신 페이지대로 최신 소스를 받아서 다시 PR 드립니다.
아직 git이 미숙해서 번거롭게 해드린점 죄송합니다 😢
문제되는 부분이 있으면 알려주시면 감사하겠습니다.

1-js / 07-object-properties / 02-property-accessors 1차 번역

---

1-js/08-prototypes/02-function-prototype/4-new-object-same-constructor/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#359 [함수의 prototype 프로퍼티]과제2 문제 번역

---

1-js/08-prototypes/02-function-prototype/1-changing-prototype/solution.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#359 [함수의 prototype 프로퍼티] 과제1 정답 번역

---

1-js/08-prototypes/03-native-prototypes/1-defer-to-prototype/solution.md
1-js/08-prototypes/03-native-prototypes/1-defer-to-prototype/task.md
1-js/08-prototypes/03-native-prototypes/2-defer-to-prototype-extended/solution.md
1-js/08-prototypes/03-native-prototypes/2-defer-to-prototype-extended/task.md
1-js/08-prototypes/03-native-prototypes/article.md

기존에 열었던  PR의 author 를 수정하는 과정에서 에러가 발생하여 부득이 하게 다시 PR 을 열게 되었습니다. 
기존에 리뷰해주신 내용 반영 하였으며 수정된 부분 리뷰 부탁 드립니다. :+1

1-js/08-prototypes/03-native-prototypes 번역입니다.

---

1-js/09-classes/01-class/1-rewrite-to-class/task.md
2-ui/4-forms-controls/1-form-elements/1-add-select-option/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[rewrite-to-class] 과제 번역 완료

---

1-js/05-data-types/11-date/article.md

* 오탈자 수정
* 혼동하기 쉬운 구문 수정
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

1-js/05-data-types/11-date/article.md 1차 리뷰

---

1-js/08-prototypes/01-prototype-inheritance/1-property-after-delete/solution.md
1-js/08-prototypes/01-prototype-inheritance/1-property-after-delete/task.md
1-js/08-prototypes/01-prototype-inheritance/2-search-algorithm/solution.md
1-js/08-prototypes/01-prototype-inheritance/2-search-algorithm/task.md
1-js/08-prototypes/01-prototype-inheritance/3-proto-and-this/solution.md
1-js/08-prototypes/01-prototype-inheritance/3-proto-and-this/task.md
1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/solution.md
1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
---
과제의 문제와 답을 나누기가 애매해서 커밋 단위만 나눠서 보냈습니다.
혹여 문제가 있다면 알려주세요. 바로 고치겠습니다.
꼼꼼히 리뷰해주셔서 항상 감사합니다. (저도 꼼꼼히 체크하겠습니다 😅)

(#246) 프로토타입 상속 과제 번역

---

1-js/09-classes/06-instanceof/1-strange-instanceof/solution.md
1-js/09-classes/06-instanceof/1-strange-instanceof/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[instanceof] 과제 번역

---

1-js/05-data-types/11-date/1-new-date/solution.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[Date 객체와 날짜] 과제1, 해답 번역

---

1-js/05-data-types/11-date/3-weekday/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[Date 객체와 날짜] 과제3, 문제 번역

---

1-js/05-data-types/11-date/1-new-date/task.md

> # Pull Request 체크리스트
> ## TODO
> * [x]  [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
>   
>   * [x]  줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
>   * [x]  [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
>   * [x]  공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`)을 비롯한 모든 특수문자는 그대로 두셨나요?
> * [x]  [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
> * [x]  PR 하나엔 번역문 하나만 넣으셨나요?
> * [x]  의미 있는 커밋 메시지를 작성하셨나요?
>   
>   * 예시
>     
>     * [프락시] 번역
>     * [프락시] 과제 번역
>     * [if문과 조건부 연산자 '?'] 리뷰
>     * [주석] 2차 리뷰
>     * [Date 객체와 날짜] 번역

[Date 객체와 날짜] 과제1, 문제 번역

---

1-js/05-data-types/11-date/2-get-week-day/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[Date 객체와 날짜] 과제2, 문제 번역

---

1-js/05-data-types/11-date/5-last-day-of-month/solution.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[Data 객체와 날짜]과제5, 해답번역

---

1-js/05-data-types/11-date/3-weekday/_js.view/solution.js

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[Date 객체와 날짜] 과제3, 해답 번역

---

2-ui/1-document/08-styles-and-classes/2-create-notification/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[styles-and-classes] 과제 번역

---

1-js/11-async/08-async-await/03-async-from-regular/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#419 [async와 await]과제3, 문제 번역

---

1-js/11-async/08-async-await/02-rewrite-async-2/solution.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#419 [async와 await] 과제2, 해답 번역

---

1-js/11-async/08-async-await/01-rewrite-async/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#419 [async와 await] 과제1, 문제 번역

---

1-js/11-async/08-async-await/01-rewrite-async/solution.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#419 [async와 await] 과제1, 해답 번역

---

1-js/11-async/08-async-await/02-rewrite-async-2/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#419 [async와 await] 과제2, 문제 번역

---

1-js/11-async/08-async-await/03-async-from-regular/solution.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#419 [async와 await] 과제3, 해답 번역

---

1-js/10-error-handling/2-custom-errors/1-format-error/task.md

[SyntaxError] 과제 번역
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[SyntaxError] 과제 번역

---

1-js/09-classes/03-static-properties-methods/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[정적 메서드와 정적 프로퍼티] 1차 리뷰

---

2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/task.md

[예금 계산기] 과제 번역
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[예금 계산기] 과제 번역

---

4-binary/02-text-decoder/article.md

[텍스트 디코더] 본문 번역
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[텍스트 디코더] 본문 번역

---

1-js/11-async/04-promise-error-handling/01-error-async/solution.md
1-js/11-async/04-promise-error-handling/01-error-async/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

 [Error handling with promises] 과제 번역

---

1-js/10-error-handling/1-try-catch/1-finally-or-code-after/solution.md
1-js/10-error-handling/1-try-catch/1-finally-or-code-after/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[Error handling, "try..catch"] 과제번역

---

1-js/08-prototypes/04-prototype-methods/2-dictionary-tostring/solution.md
1-js/08-prototypes/04-prototype-methods/2-dictionary-tostring/task.md
1-js/08-prototypes/04-prototype-methods/3-compare-calls/solution.md
1-js/08-prototypes/04-prototype-methods/3-compare-calls/task.md

본 PR은 [Prototype methods]에 대한 과제 전체와 해답 전체에 대한 내용이 담겨있습니다.
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[Prototype methods]과제 번역 및 해답

---

9-regular-expressions/01-regexp-introduction/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

Punctuations fix

---

1-js/03-code-quality/05-testing-mocha/article.md

중첩 describe 예제코드의 불필요한 backtick 삭제
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[테스트 자동화와 Mocha] 코드예제 오타 수정

---

1-js/11-async/05-promise-api/article.md

``` patch
- 여러 요청 충 하나가
+ 여러 요청 중 하나가
```
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[프라미스] Promise.allSettled 본문 오타 수정

---

1-js/02-first-steps/03-strict-mode/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[엄격모드] 자연스러운 표현

---

1-js/04-object-basics/04-object-methods/2-check-syntax/solution.md
1-js/04-object-basics/04-object-methods/4-object-property-this/task.md
1-js/04-object-basics/04-object-methods/7-calculator/task.md
1-js/04-object-basics/04-object-methods/8-chain-calls/solution.md
1-js/04-object-basics/04-object-methods/8-chain-calls/task.md

- `1-js` > `04-object-basics` > `04-object-methods` 내의 번역되지 않은 잔여 과제/해답 모두 번역하였습니다(Closes #463 ).
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[메서드와 'this'] 과제 번역

---

2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/solution.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#471 [주요 노드 프로퍼티] 과제3, 해답 번역

---

2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#471 [주요 노드 프로퍼티] 과제3, 문제 번역

---

2-ui/1-document/05-basic-dom-node-properties/4-where-document-in-hierarchy/solution.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#471 [주요 노드 프로퍼티] 과제4, 문제 번역

---

1-js/09-classes/06-instanceof/article.md
2-ui/1-document/05-basic-dom-node-properties/article.md

Closes #472 
```diff
- 계층구조
+ 계층 구조
```
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

계층 구조 띄어쓰기 통일

---

1-js/02-first-steps/10-ifelse/article.md

코드 예제내에 나이가 `age < 9`로 되어있는 반면에, 
아래 설명과 그 아래 예제에서는 `age < 3`으로 일치하지 않아 `age < 3`으로 수정
(아기라면 3살 이하가 맞는거 같네요 ^^)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[조건부 연산자 if와 ?] 코드예제 오타 수정

---

8-web-components/1-webcomponents-intro/article.md

[From the orbital height]본문 번역
전에 리뷰해주신 PR을 했던 리포지터리를 delete하고 새로 포크 했었습니다. 그래서 해당 PR에서 작업을 할 수가 없어 새로 PR하겠습니다.
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[From the orbital height]본문 번역

---

8-web-components/2-custom-elements/1-live-timer/solution.md
8-web-components/2-custom-elements/1-live-timer/task.md

[라이브 타이머] 과제 번역
전에 리뷰해주신 PR을 했던 리포지터리를 delete하고 새로 포크 했었습니다. 그래서 해당 PR에서 작업을 할 수가 없어 새로 PR하겠습니다.
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[라이브 타이머] 과제 번역

---

1-js/04-object-basics/07-optional-chaining/article.md

- [V] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
- [V] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
- [V] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
- [V] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [V] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [V] PR 하나엔 번역문 하나만 넣으셨나요?
- [V] 의미 있는 커밋 메시지를 작성하셨나요?
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
PR내용
4.6 옵셔널 체이닝의 요약 2번에 오타가 있어서 수정했습니다.

옵셔널 체이닝의 요약부분 오타 수정

---

1-js/02-first-steps/14-switch/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
folk 후 PR은 처음 해보는데 제대로 한 건지 모르겠어요. 
이슈에서 본 switch문의 따옴표 오타를 수정했습니다.

[switch문] 오타 수정 #501

---

1-js/09-classes/02-class-inheritance/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
#544

[클래스 상속] 오타 수정

---

1-js/07-object-properties/02-property-accessors/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[프로퍼티 getter와 setter] 오타 수정

---

2-ui/2-events/02-bubbling-and-capturing/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[버블링과 캡쳐링] 원문 삭제

---

3-frames-and-windows/index.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[프레임과 윈도우] 큰 주제 번역

---

8-web-components/index.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹 컴포넌트] 주제 번역

---

2-ui/1-document/07-modifying-document/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
관련 이슈: #533

[문서 수정하기] 번역 오류 수정 #533

---

1-js/02-first-steps/08-operators/4-fix-prompt/solution.md
1-js/02-first-steps/08-operators/4-fix-prompt/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
task와 solution을 같이 번역했습니다.

기본 연산자와 수학 과제 번역

---

8-web-components/index.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹 컴포넌트] 인코딩 깨지는 커밋 revert 하고 대단원 제목만 번역

---

1-js/05-data-types/11-date/3-weekday/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[숫자형] 오타 수정

---

1-js/04-object-basics/01-object/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
이슈번호 #737

[신규 번역]파트1 객체4.1 Summary 번역누락반영 #737

---

9-regular-expressions/05-regexp-multiline-mode/article.md

병합 충돌에서 계속 문제가 발생해 브랜치를 완전히 새로 생성해서 기존 [PR](https://github.com/javascript-tutorial/ko.javascript.info/pull/605)이 닫혔습니다.
그래서 새롭게 PR을 올립니다.

[여러 행 모드] 번역

---

1-js/05-data-types/10-destructuring-assignment/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[주석 수정] 자료구조와 자료형 - 구조 분해 할당

---

1-js/05-data-types/10-destructuring-assignment/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정] 파트1 5.10 구조분해할당 #774

---

1-js/07-object-properties/02-property-accessors/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정]Part1 7.2 프로퍼티 getter와 setter #795

---

1-js/04-object-basics/08-symbol/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
이슈번호 #793

[오타수정]파트1 4.7심볼형 오타수정 #793

---

1-js/09-classes/02-class-inheritance/article.md

console.log의 결과로 출력되는 메시지가 영어로 출력되어 있어서 한글로
수정했습니다.
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정] 파트 1 - 9.2 클래스 상속

---

1-js/05-data-types/03-string/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[어색한 표현 수정] 파트1 5.3 문자열 #772

---

2-ui/1-document/07-modifying-document/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[문서 수정하기] 누락부분 번역

---

1-js/08-prototypes/02-function-prototype/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정] Part1 8.2 함수의 prototype 프로퍼티 #805

---

1-js/05-data-types/06-iterable/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[번역] Part1 5.6 iterable 객체 누락된 부분 번역 #756

---

1-js/02-first-steps/04-variables/article.md

[번역] Part1 변수와 상수 warn 부분

---

2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/solution.view/index.html
2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/source.view/index.html
2-ui/4-forms-controls/3-events-change-input/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[신규 번역]파트2 4.3이벤트 원문번역 #641

---

1-js/11-async/02-promise-basics/article.md

`전될`을 `전달`로 수정했습니다.
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타 수정] 파트 1 - 11.2 프라미스

---

1-js/09-classes/05-extend-natives/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[어색한 표현 수정] Part1 9.5 내장 클래스 확장하기

---

1-js/09-classes/01-class/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
번역하다 보니 같은 내용이 중복된 부분이 있어, 영문 튜토리얼을 확인 하였더니 영문 튜토리얼은 중복된 부분이 없는 것을 확인했습니다. 그래서 영문 튜토리얼의 줄 수에 맞추어 중복 내용 삭제하고 번역했습니다.

[번역] Part1 9.1 클래스와 기본 문법 미번역된 부분 번역 #807

---

1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/solution.md
1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/task.md
1-js/06-advanced-functions/10-bind/3-second-bind/solution.md
1-js/06-advanced-functions/10-bind/3-second-bind/task.md
1-js/06-advanced-functions/10-bind/4-function-property-after-bind/solution.md
1-js/06-advanced-functions/10-bind/4-function-property-after-bind/task.md
1-js/06-advanced-functions/10-bind/5-question-use-bind/solution.md
1-js/06-advanced-functions/10-bind/5-question-use-bind/task.md
1-js/06-advanced-functions/10-bind/6-ask-partial/solution.md
1-js/06-advanced-functions/10-bind/6-ask-partial/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[1.6.10 함수 바인딩] 과제&해답 번역

---

1-js/04-object-basics/01-object/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[객체] - Object with const can be changed 번역 #696

---

1-js/11-async/02-promise-basics/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오번역수정] 11.2 프라미스 #844

---

1-js/08-prototypes/02-function-prototype/1-changing-prototype/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타 수정]8.2 함수의 prototype 프로퍼티 #840

---

1-js/09-classes/02-class-inheritance/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

Part1 9.2 클래스 상속 미번역된 부분 번역

---

1-js/05-data-types/02-number/1-sum-interface/solution.md
1-js/05-data-types/02-number/1-sum-interface/task.md
1-js/05-data-types/02-number/2-why-rounded-down/solution.md
1-js/05-data-types/02-number/2-why-rounded-down/task.md
1-js/05-data-types/02-number/3-repeat-until-number/solution.md
1-js/05-data-types/02-number/3-repeat-until-number/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[과제번역] Part 1. 5.2 number: task1, solution1, task2, solution2

---

2-ui/2-events/04-default-browser-action/1-why-return-false-fails/solution.md
2-ui/2-events/04-default-browser-action/1-why-return-false-fails/task.md
2-ui/2-events/04-default-browser-action/2-catch-link-navigation/solution.md
2-ui/2-events/04-default-browser-action/2-catch-link-navigation/task.md
2-ui/2-events/04-default-browser-action/3-image-gallery/solution.md
2-ui/2-events/04-default-browser-action/3-image-gallery/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[과제번역] Part2. 2.4 Browser default actions 과제 번역 #711

---

CONTRIBUTING.md
README.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
README.md 수정 및 CONTRIBUTING.md 추가했습니다.
작업 결과는 아래 링크에서 확인 가능합니다. 
(contributing.md파일이 원본 저장소에 아직 생성되지 않았기 때문에 README.md에서 링크 클릭 시 404로 나옵니다. PR이 반영되면 정상적으로 보여질 것입니다.)
- [README.md](https://github.com/KimHunJin/ko.javascript.info/tree/document-%23861/contributing)
- [CONTRIBUTING.md](https://github.com/KimHunJin/ko.javascript.info/blob/document-%23861%2Fcontributing/CONTRIBUTING.md)

#861 [개선제안] CONTRIBUTING.md 초안 작성 및 README.md 수정

---

1-js/08-prototypes/03-native-prototypes/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오번역수정] 네이티브 프로토타입 #848

---

1-js/05-data-types/03-string/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오번역수정] 5.3 문자열 #842

---

5-network/01-fetch/01-fetch-users/_js.view/source.js
5-network/01-fetch/01-fetch-users/_js.view/test.js
5-network/01-fetch/01-fetch-users/solution.md
5-network/01-fetch/01-fetch-users/task.md

- [✅] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
- [✅] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
- [✅] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
- [✅] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [✅] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [✅] PR 하나엔 번역문 하나만 넣으셨나요?
- [✅] 의미 있는 커밋 메시지를 작성하셨나요?
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[fetch] - 과제 번역 #679

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line45(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line31(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line26(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line22(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line1(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line63 (#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line9(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓]번역,line17(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line29(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line65(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line39(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line15(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line54(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line52(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line33(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line5(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소킷] 번역, line67(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line69(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line71(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line50(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line40(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line53(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line18(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역, line28(#883)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

line2 번역#920

---

CONTRIBUTING.md

[강조/인용시 사용되는 따옴표 규칙](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EA%B0%95%EC%A1%B0%EC%9D%B8%EC%9A%A9%EC%8B%9C-%EC%82%AC%EC%9A%A9%EB%90%98%EB%8A%94-%EB%94%B0%EC%98%B4%ED%91%9C)에 따라 CONTRIBUTING.md 파일의 26번째 줄 강조 부분의 큰따옴표를 작은따옴표로 수정했습니다.
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오번역수정] CONTRIBUTING.md 파일 line26 강조부분 작은 따옴표로 수정

---

1-js/12-generators-iterators/1-generators/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정] 제너레이터 본문내 전개 문법 링크 깨짐 #917

---

9-regular-expressions/10-regexp-greedy-and-lazy/1-lazy-greedy/task.md

과제 코드에 `);` 이라는 잘못된 코드가 들어가있어서 실행하는데 오류가 발생합니다. 따라서 삭제했습니다.
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타 수정] 파트3 - 7.10 Greedy and lazy quantifiers

---

2-ui/1-document/07-modifying-document/1-createtextnode-vs-innerhtml/solution.md
2-ui/1-document/07-modifying-document/1-createtextnode-vs-innerhtml/task.md
2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.md
2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.view/index.html
2-ui/1-document/07-modifying-document/10-clock-setinterval/source.view/index.html
2-ui/1-document/07-modifying-document/10-clock-setinterval/task.md
2-ui/1-document/07-modifying-document/11-append-to-list/solution.md
2-ui/1-document/07-modifying-document/11-append-to-list/task.md
2-ui/1-document/07-modifying-document/12-sort-table/solution.md
2-ui/1-document/07-modifying-document/12-sort-table/source.view/index.html
2-ui/1-document/07-modifying-document/12-sort-table/task.md
2-ui/1-document/07-modifying-document/4-clear-elem/solution.md
2-ui/1-document/07-modifying-document/4-clear-elem/task.md
2-ui/1-document/07-modifying-document/5-why-aaa/solution.md
2-ui/1-document/07-modifying-document/5-why-aaa/task.md
2-ui/1-document/07-modifying-document/6-create-list/solution.md
2-ui/1-document/07-modifying-document/6-create-list/task.md
2-ui/1-document/07-modifying-document/7-create-object-tree/build-tree-dom.view/index.html
2-ui/1-document/07-modifying-document/7-create-object-tree/innerhtml.view/index.html
2-ui/1-document/07-modifying-document/7-create-object-tree/solution.md
2-ui/1-document/07-modifying-document/7-create-object-tree/source.view/index.html
2-ui/1-document/07-modifying-document/7-create-object-tree/task.md
2-ui/1-document/07-modifying-document/8-tree-count/solution.md
2-ui/1-document/07-modifying-document/8-tree-count/solution.view/index.html
2-ui/1-document/07-modifying-document/8-tree-count/source.view/index.html
2-ui/1-document/07-modifying-document/8-tree-count/task.md
2-ui/1-document/07-modifying-document/9-calendar-table/solution.md
2-ui/1-document/07-modifying-document/9-calendar-table/solution.view/index.html
2-ui/1-document/07-modifying-document/9-calendar-table/source.view/index.html
2-ui/1-document/07-modifying-document/9-calendar-table/task.md

- [✅] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
- [✅] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
- [✅] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
- [✅] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [✅] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [✅] PR 하나엔 번역문 하나만 넣으셨나요?
- [✅] 의미 있는 커밋 메시지를 작성하셨나요?
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
---
과제 분량이 생각보다 많아서 먼저 절반 분량 리뷰를 요청드립니다! :)
- 맞춤법 검사 중 "~방법이 구체적으로 정해져 있으므로" 라는 부분을 "있음으로" 고쳐야 한다고 나왔는데, "까닭이나 근거를 나타낼 때" 는 "있으므로" 를 사용하는 것이 옳다는 [국립국어원 …

[과제 번역] - 문서 수정하기 #689

---

1-js/04-object-basics/07-optional-chaining/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정] Part 1 4.6 옵셔널 체이닝 '?.' - 옵셔널 체이닝이 필요한 이유 #939

---

2-ui/3-event-details/4-mouse-drag-and-drop/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
- 기존 PR : https://github.com/javascript-tutorial/ko.javascript.info/pull/833
- 기존 있던 저장소를 upstream repository와 동기화 시키는 과정에서 rebase로 인해 사용자들의 라이센스 문제가 발생해 새로 PR올립니다.
(merge를 선택했어야 했는데, rebase로 머지하면서 다른 기여자분들의 작업까지 한 번에 올라가 CLA 승인이 이뤄지지 않더군요..)

#713 [번역][Drag & Drop] 드래그 앤 드랍 번역

---

1-js/09-classes/01-class/article.md

원문에 나와있지 않은 내용(심지어 잘못된 내용)이 존재해서 제거하였습니다.
[원문] "We can also assign values using more complex expressions and function calls"
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오번역 수정] 파트 1.9.1 - 원문에 없는 내용 제거 #966

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

 #883 [웹소켓] 번역 - line 116

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883 [웹소켓] 번역 - line 93

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883 [웹소켓] 번역 - line 130

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883 [웹소켓] 번역 - line 65

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883 [웹소켓] 번역 - line 124

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883 [웹소켓] 번역 - line 15

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883 [웹소켓] 번역 - line 132

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883 [웹소켓] 번역 - line 41, 63

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883 [웹소켓] 번역 - line 148

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883 [웹소켓] 번역 - line 75

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883 [웹소켓] 번역 - line 95

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883 [웹소켓] 번역 - line 118

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883 [웹소켓] 번역 - line 122

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역(#883) - line 79

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883 [웹소켓] 번역 - line 112

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883[웹소켓]번역 - line 91

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883 [웹소켓] 번역 - line 110

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883 [웹소켓] 번역 - line 97

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883 [웹소켓] 번역 - line 114

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883 [웹소켓] 번역 - line 94

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#883 [웹소켓] 번역 - line 120

---

2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/source.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[과제 번역] 마우스 이벤트 과제, Selectable list의 데모 번역(#1069)

---

2-ui/1-document/05-basic-dom-node-properties/2-tree-info/solution.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[과제 번역] 주요 노드 프로퍼티 과제(Count descendants)의 해답 번역 (#1068)

---

2-ui/1-document/05-basic-dom-node-properties/2-tree-info/source.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[과제 번역] 주요 노드 프로퍼티 과제(Count descendants)의 데모 번역 (#1068)

---

2-ui/1-document/05-basic-dom-node-properties/2-tree-info/source.view/index.html

This reverts commit 1aecd8fe8f29680da749f1a703e74a31e4683512.
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

Revert "[과제 번역] 주요 노드 프로퍼티 과제(Count descendants)의 데모 번역 (#1068)"

---

1-js/05-data-types/08-weakmap-weakset/01-recipients-read/solution.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타 수정] Part1 5.8 위크맵과 위크셋 과제1 #1081

---

2-ui/1-document/03-dom-navigation/4-select-diagonal-cells/solution.md
2-ui/1-document/03-dom-navigation/4-select-diagonal-cells/task.md

Closes #1043 
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[과제번역] Part 2. 1.3 Walking the DOM #1043

---

2-ui/4-forms-controls/index.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[대단원 번역] 폼과 폼 조작 (#1089)

---

2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

 [과제 번역] focus와 blur 과제, Edit TD on click 문제 번역 (#1092)

---

2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/source.view/index.html
2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[과제 번역] focus와 blur 과제, Keyboard-driven mouse 문제 번역 (#1095)

---

2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/solution.md
2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/solution.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[과제 번역] focus와 blur 과제, Keyboard-driven mouse 해답 번역 (#1096)

---

2-ui/4-forms-controls/2-focus-blur/3-editable-div/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[과제 번역] focus와 blur 과제, Editable div의 문제 번역(#1090)

---

2-ui/4-forms-controls/2-focus-blur/3-editable-div/solution.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[과제 번역] focus와 blur 과제, Editable div의 해답 번역(#1091)

---

2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/solution.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

 [과제 번역] focus와 blur 과제, Edit TD on click 해답 번역 (#1093)

---

2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/solution.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[과제 번역] 마우스 이벤트 과제, Selectable list의 해답 번역(javascript-tutorial#1069)

---

2-ui/1-document/05-basic-dom-node-properties/2-tree-info/solution.view/index.html
2-ui/1-document/05-basic-dom-node-properties/2-tree-info/source.view/index.html
2-ui/1-document/05-basic-dom-node-properties/2-tree-info/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

Issue #1068

---

1-js/02-first-steps/05-types/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[번역 수정]자바스크립트기본-자료형 호환성 이슈 부분(#1109)

---

1-js/13-modules/01-modules-intro/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[신규 번역] 'Part 1. 13.1 모듈 소개' 중간에 주의사항 #1084

---

1-js/09-classes/05-extend-natives/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정] part 1 9.5 내장클래스 확장하기 #1136

---

1-js/08-prototypes/03-native-prototypes/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정] Part 1 8.3 네이티브 프로토타입 #1129

---

1-js/08-prototypes/02-function-prototype/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정] Part 1 8.2 함수의 prototype 프로퍼티 #1127

---

2-ui/5-loading/01-onload-ondomcontentloaded/article.md

- [ ✔] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
- [✔ ] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
- [ ✔] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
- [✔ ] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [✔ ] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [ ✔] PR 하나엔 번역문 하나만 넣으셨나요?
- [✔ ] 의미 있는 커밋 메시지를 작성하셨나요?
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정] Part 2 5.1 DOMContentLoaded, load, beforeunload, unload 이벤트#1143

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] line 168 번역(#1156)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] line 172 번역(#1156)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] line 167 번역(#1156)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] line 163, 165 번역(#1156)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] line 180 번역 (#1156)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] line 170 번역(#1156)

---

5-network/11-websocket/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 충북대 특강 실습용

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line127(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line13(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line23(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line52(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line69(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line54(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line163(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line8(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line59(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line115(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line19(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line64(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line119(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line86(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData번역] - line21(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line141(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line165(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line169(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line50(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line76(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line171(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line189(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line113(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData]번역 - line28(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

인코딩 깨지는 코드들 롤백

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

 [FormData] 번역 - line4(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

re_[FormData] 번역 - line64(#1232)

---

5-network/02-formdata/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[FormData] 번역 - line121(#1232)

---

5-network/02-formdata/article.md
5-network/02-formdata/post.view/server.js

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

 [FormData] 번역

---

1-js/08-prototypes/02-function-prototype/article.md

- [✔ ] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
- [✔ ] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
- [ ✔] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
- [ ✔] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [ ✔] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [ ✔] PR 하나엔 번역문 하나만 넣으셨나요?
- [ ✔] 의미 있는 커밋 메시지를 작성하셨나요?
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[#1220] 함수의 prototype 프로퍼티 꺽쇠에 의한 오탈자 이슈 수정

---

4-binary/index.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이진 데이터와 파일] 대단원 설명 번역(#1299)

---

2-ui/2-events/03-event-delegation/1-hide-message-delegate/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제1 문제 번역 - line 7(#1300)

---

2-ui/99-ui-misc/03-event-loop/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 루프와 매크로태스크, 마이크로태스크] 본문 내 '웹 워커' 번역 - line 335(#1298)

---

2-ui/99-ui-misc/03-event-loop/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 루프와 매크로태스크, 마이크로태스크] 본문 내 '웹 워커' 번역 - line 337(#1298)

---

2-ui/2-events/03-event-delegation/1-hide-message-delegate/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제1 문제 번역 - line 13(#1300)

---

4-binary/index.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이진 데이터와 파일] 대단원 설명 번역 - line3(#1299)

---

2-ui/2-events/03-event-delegation/1-hide-message-delegate/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제1 문제 번역 - line 9(#1300)

---

2-ui/2-events/03-event-delegation/1-hide-message-delegate/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제1 문제 번역 - line 5(#1300)

---

2-ui/2-events/03-event-delegation/3-sortable-table/solution.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 해답 번역 - line 43(#1312)

---

2-ui/2-events/03-event-delegation/2-sliding-tree/solution.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제2 해답 번역 - line 4(#1311)

---

2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제4 문제 번역 - line 31(#1313)

---

2-ui/2-events/03-event-delegation/3-sortable-table/solution.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 해답 샘플 번역 - line 29(#1312)

---

2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제4 문제 번역 - line 28(#1313)

---

2-ui/2-events/03-event-delegation/3-sortable-table/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 문제 번역 - line 37(#1312)

---

2-ui/2-events/03-event-delegation/3-sortable-table/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 문제 번역 - line 17(#1312)

---

2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제4 문제 번역 - line 25(#1313)

---

2-ui/2-events/03-event-delegation/3-sortable-table/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 문제 번역 - line 28(#1312)

---

2-ui/2-events/03-event-delegation/3-sortable-table/source.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 해답 샘플 번역 - line 35(#1312)

---

2-ui/2-events/03-event-delegation/3-sortable-table/source.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 해답 샘플 번역 - line 43(#1312)

---

2-ui/2-events/03-event-delegation/3-sortable-table/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 문제 번역 - line 7(#1312)

---

2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제4 문제 번역 - line 21(#1313)

---

2-ui/2-events/03-event-delegation/3-sortable-table/solution.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 해답 번역 - line 63(#1312)

---

2-ui/2-events/03-event-delegation/4-behavior-tooltip/source.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제4 해답 샘플 번역 - line 9(#1313)

---

2-ui/2-events/03-event-delegation/3-sortable-table/solution.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 해답 번역 - line 35(#1312)

---

2-ui/2-events/03-event-delegation/3-sortable-table/solution.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 해답 번역 - line 39(#1312)

---

2-ui/2-events/03-event-delegation/4-behavior-tooltip/source.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제4 해답 샘플 번역 - line 32(#1313)

---

2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제4 문제 번역 - line 32(#1313)

---

2-ui/2-events/03-event-delegation/3-sortable-table/source.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 해답 샘플 번역 - line 28(#1312)

---

2-ui/2-events/03-event-delegation/3-sortable-table/solution.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 해답 번역 - line 65(#1312)

---

2-ui/2-events/03-event-delegation/2-sliding-tree/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제2 문제 번역 - line 11(#1311)

---

2-ui/2-events/03-event-delegation/3-sortable-table/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 문제 번역 - line 24(#1312)

---

2-ui/2-events/03-event-delegation/3-sortable-table/source.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 해답 번역 - line 51(#1312)

---

2-ui/2-events/03-event-delegation/3-sortable-table/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 문제 번역 - line 16(#1312)

---

2-ui/2-events/03-event-delegation/3-sortable-table/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 문제 번역 - line 9(#1312)

---

2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제4 문제 번역 - line 7(#1313)

---

2-ui/2-events/03-event-delegation/3-sortable-table/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 문제 번역 - line 39(#1312)

---

2-ui/2-events/03-event-delegation/3-sortable-table/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 문제 번역 - line 35(#1312)

---

2-ui/2-events/03-event-delegation/3-sortable-table/solution.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 해답 번역 - line 74(#1312)

---

2-ui/2-events/03-event-delegation/3-sortable-table/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 문제 번역 - line 5(#1312)

---

2-ui/2-events/03-event-delegation/3-sortable-table/source.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 해답 샘플 번역 - line 57(#1312)

---

2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제4 문제 번역 - line 9(#1313)

---

2-ui/2-events/03-event-delegation/2-sliding-tree/solution.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제2 해답 예제코드 번역 - line62(#1311)

---

6-data-storage/02-localstorage/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
-  https://github.com/javascript-tutorial/ko.javascript.info/issues/1400

[오타수정] Part 3 4.2 localStorage와 sessionStorage 문자열만 사용 #1400

---

2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제4 문제 번역 - line 14(#1313)

---

2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제4 문제 번역 - line 34(#1313)

---

2-ui/2-events/03-event-delegation/2-sliding-tree/source.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제2 문제 예제코드 번역 추가(#1311)

---

2-ui/2-events/03-event-delegation/4-behavior-tooltip/source.view/index.html

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제4 해답 샘플 번역 - line 13(#1313)

---

2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제4 문제 번역 - line 38(#1313)

---

2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제4 문제 번역 - line 11(#1313)

---

2-ui/2-events/03-event-delegation/2-sliding-tree/solution.md
2-ui/2-events/03-event-delegation/2-sliding-tree/solution.view/index.html
2-ui/2-events/03-event-delegation/2-sliding-tree/source.view/index.html
2-ui/2-events/03-event-delegation/2-sliding-tree/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제2 번역 (#1311)

---

2-ui/2-events/03-event-delegation/3-sortable-table/solution.view/index.html
2-ui/2-events/03-event-delegation/3-sortable-table/source.view/index.html
2-ui/2-events/03-event-delegation/3-sortable-table/task.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[이벤트 위임] 과제3 번역(#1312)

---

1-js/02-first-steps/04-variables/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정] Part 1 - 2.4 변수와 상수 (이슈 #1425)

---

1-js/02-first-steps/06-alert-prompt-confirm/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정] Part 1 2.6 alert, prompt, confirm을 이용한 상호작용 #1445

---

.github/pull_request_template.md

#1487 
PR 템플릿에 Summary 헤딩을 추가하였습니다.
주석은 간단하게 `` 이런 식으로 첨부해놓았습니다. 주석에 첨부할 내용이나 더 추가및 수정해야할 내용이 있으면 알려주시면 감사하겠습니다.
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[PR 템플릿 개선] PR 템플릿에 Summary 헤딩 추가(#1487)

---

2-ui/1-document/01-browser-environment/article.md

- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정] fix: Part 2 1.1 DOM window.sayHi() 작동을 위해 오타수정 (#1518)

---

2-ui/1-document/04-searching-elements-dom/article.md

[Part 2 1.4 getElement*, querySelector*로 요소 검색하기](https://ko.javascript.info/searching-elements-dom) 의 [getElementsBy*](https://ko.javascript.info/searching-elements-dom#ref-693) 섹션의 마지막 예시에서 form이 fomr으로 오타가 났다는 것을 발견했고, 오타를 수정하기 위해 PR 합니다. 
fomr -> form
[이슈 링크](https://github.com/javascript-tutorial/ko.javascript.info/issues/1522)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

fix: [오타수정] Part 2 1.4 getElementsBy* 섹션 form 오타 (#1522)

---

2-ui/2-events/01-introduction-browser-events/article.md

[Part 2 2.1 - 브라우저 이벤트 소개 중 이벤트 핸들러 섹션](https://ko.javascript.info/introduction-browser-events#ref-310)에 번역 누락된 문장을 발견했습니다. 
또한 같은 섹션에 띄어쓰기 오타를 발견했습니다
[연관 이슈 1537](https://github.com/javascript-tutorial/ko.javascript.info/issues/1537)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정] Part 2 2.1 - 브라우저 이벤트 소개 중 이벤트 핸들러 섹션 오타 두 가지 수정

---

1-js/02-first-steps/10-ifelse/2-check-standard/ifelse_task2/index.html

if와 '?'를 사용한 조건 처리 과제 2번의 해답에서, [강조/인용 시 사용되는 따옴표](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EA%B0%95%EC%A1%B0%EC%9D%B8%EC%9A%A9%EC%8B%9C-%EC%82%AC%EC%9A%A9%EB%90%98%EB%8A%94-%EB%94%B0%EC%98%B4%ED%91%9C)에 맞지 않게 번역되어 번역하였습니다. 
로컬서버 반영본은 아래에 첨부하였습니다.
이슈 : https://github.com/javascript-tutorial/ko.javascript.info/issues/1527
링크 : https://ko.javascript.info/ifelse - 과제 2번
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정] if와 '?'를 사용한 조건 처리 잘못된 강조 따옴표 사용(과제 2) (#1527)

---

4-binary/01-arraybuffer-binary-arrays/01-concat/task.md

https://ko.javascript.info/arraybuffer-binary-arrays
https://github.com/javascript-tutorial/ko.javascript.info/issues/1549
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[신규 번역] Part 3 2.1 ArrayBuffer, binary arrays 과제 번역(#1549)

---

1-js/04-object-basics/02-object-copy/article.md

[Part1 - 4.2chapter 참조에 의한 객체 복사](https://ko.javascript.info/object-copy)
본문에서 띄어쓰기 오타가 발견되어 수정하였습니다.
동작방식 -> 동작 방식
연관이슈 [#1577](https://github.com/javascript-tutorial/ko.javascript.info/issues/1577)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정] Part1 - 4.2 참조에 의한 객체 복사(#1577)

---

1-js/02-first-steps/07-type-conversions/article.md

링크: [형 변환 - 숫자형으로 변환](https://ko.javascript.info/type-conversions#ref-1919)
[오타수정] Part 1 - 2.7 형 변환 #1573
`undefined`은 -> `undefined`는
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정] Part 1 - 2.7 형 변환 (#1573)

---

2-ui/2-events/01-introduction-browser-events/01-hide-other/solution.view/index.html
2-ui/2-events/01-introduction-browser-events/01-hide-other/source.view/index.html
2-ui/2-events/01-introduction-browser-events/01-hide-other/task.md
2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/solution.md
2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/task.md
2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/solution.md
2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/task.md

Part 2 - 2.1 브라우저 이벤트 소개 과제 1-3의 번역을 시도했습니다.
[Hide on click](https://ko.javascript.info/introduction-browser-events#ref-319)
[Hide Self](https://ko.javascript.info/introduction-browser-events#ref-320)
[Which Handlers run?](https://ko.javascript.info/introduction-browser-events#ref-321)
[이슈 1539](https://github.com/javascript-tutorial/ko.javascript.info/issues/1539)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[신규 번역] Part 2 - 2.1 브라우저 이벤트 소개 과제 1-3 번역 (#1539)

---

2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/solution.md
2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/task.md

[신규 번역] Part 2. 2.9 Element size and scrolling 마지막 과제 (difference: CSS width versus clientWidth) 과제 및 해답 번역
[Part 2. 2.9 Element size and scrolling 마지막 과제 (difference: CSS width versus clientWidth)](https://ko.javascript.info/size-and-scroll#ref-637)에 대한 번역
[이슈 1535 링크](https://github.com/javascript-tutorial/ko.javascript.info/issues/1535)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[신규 번역] Part 2. 2.9 Element size and scrolling 마지막 과제

---

5-network/11-websocket/article.md

* line193 - Imagine, our app is generating a lot of data to send. But the user has a slow network connection, maybe on a mobile internet, outside of a city.
* 데이터 전송량이 상당한 앱을 개발하고 있다고 가정해봅시다. 그런데 우리 앱의 사용자는 모바일이나 시골같이 네트워크 속도가 느린 곳에서 앱을 사용하고 있다고 해보죠.
(fix #1606)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line193 (#1606)

---

5-network/11-websocket/article.md

[웹소켓] 기존 번역 보완 - line202 (#1616)

---

5-network/11-websocket/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line241 (#1606)

---

5-network/11-websocket/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓]번역-line-291(#1606)

---

5-network/11-websocket/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line294 (#1606)

---

5-network/11-websocket/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line269 (#1606)

---

5-network/11-websocket/article.md

[웹소켓] 번역 - line278
(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line278 (#1606)

---

5-network/11-websocket/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line271 (#1606)

---

5-network/11-websocket/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line274 (#1606)

---

5-network/11-websocket/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line233 (#1606)

---

5-network/11-websocket/article.md

[웹소켓] 번역 - line281 (#1606) 번역 완료
(fix #일이삼)
#1606 
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line281 (#1606)

---

5-network/11-websocket/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line252 (#1606)

---

5-network/11-websocket/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line255 (#1606)

---

5-network/11-websocket/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line250 (#1606)

---

5-network/11-websocket/article.md

웹소켓 245번째 줄 번역
(fix #일이삼)
#1606 
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line245 (#1606)

---

5-network/11-websocket/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line247 (#1606)

---

5-network/11-websocket/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line276 (#1606)

---

5-network/11-websocket/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line270 (#1606)

---

5-network/11-websocket/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line293 (#1606)

---

5-network/11-websocket/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line287 (#1606)

---

5-network/11-websocket/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line246 (#1606)

---

2-ui/4-forms-controls/1-form-elements/1-add-select-option/task.md

[Part2 4.1 폼 프로퍼티와 메서드](https://ko.javascript.info/form-elements)의 select에 옵션 추가하기 과제 부분에서 번역이 누락된 부분을 발견했습니다.
번역이 누락된 부분을
Note, if you’ve done everything right, your alert should show `blues`.
=> 모든 항목을 올바르게 수행했다면 얼럿창에 `blues`가 출력됩니다.
와 같이 수정하였습니다.
fix #1638 
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정] Part2 4.1 폼 프로퍼티와 메서드 누락된 번역 수정(#1638)

---

5-network/11-websocket/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line243 (#1606)

---

5-network/11-websocket/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[웹소켓] 번역 - line240 (#1606)

---

9-regular-expressions/09-regexp-quantifiers/1-find-text-manydots/solution.md
9-regular-expressions/09-regexp-quantifiers/1-find-text-manydots/task.md
9-regular-expressions/09-regexp-quantifiers/2-find-html-colors-6hex/solution.md
9-regular-expressions/09-regexp-quantifiers/2-find-html-colors-6hex/task.md

Part 9의 9.9 과제 2개를 번역하였습니다.
#1601
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[과제번역] Part9. 9.9 과제 번역 (#1601)

---

5-network/10-long-polling/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[롱폴링] 본문 번역 - line3 (#1659)

---

5-network/10-long-polling/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[롱폴링] 본문 번역 - line1 (#1659)

---

5-network/10-long-polling/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[롱폴링] 본문 번역 - line21 (#1659)

---

5-network/10-long-polling/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[롱폴링] 본문 번역 - line68 (#1659)

---

5-network/10-long-polling/article.md

* 롱 폴링 문서 라인 5 수정
(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[롱폴링] 본문 번역 - line5 (#1659)

---

5-network/10-long-polling/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[롱폴링] 본문 번역 - line17 (#1659)

---

5-network/10-long-polling/article.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[롱폴링] 본문 번역 - line23 (#1659)

---

2-ui/1-document/05-basic-dom-node-properties/article.md

fix #1679 
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타수정] Part2 1.5 주요 노드 프로퍼티 (#1679)

---

1-js/06-advanced-functions/09-call-apply-decorators/article.md

'구분할 수 **있**습니다'를  '구분할 수 **없**습니다'로 변경하였습니다.
(fix #1686)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오번역수정] Part 1 - 6.9 call/apply와 데코레이터, 포워딩 (#1686)

---

1-js/99-js-misc/01-proxy/03-observable/task.md

사소하지만 공부중에 오타를 확인해서 보냅니다.
Reflect 부분 번역 업데이트가 안됐는데, 가능하면 도전해보겠습니다.
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[오타 수정] Part 1.14.1 Proxy와 Reflect

---

1-js/05-data-types/02-number/4-endless-loop-error/task.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

1711 task translate

---

1-js/05-data-types/02-number/4-endless-loop-error/solution.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

1711 task 4 번역

---

1-js/05-data-types/02-number/4-endless-loop-error/solution.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

1711 task translate donghyun

---

1-js/05-data-types/02-number/4-endless-loop-error/solution.md
1-js/05-data-types/02-number/4-endless-loop-error/task.md

(fix #일이삼)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[신규 번역] 숫자쳥 네번째 과제 번역 #1711

---

1-js/05-data-types/02-number/8-random-min-max/task.md

#1724 
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#1724 random min max 과제 번역11번째줄

---

1-js/05-data-types/02-number/8-random-min-max/solution.md

random-min-max 3번째 문장을 번역했습니다
#1723 
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[신규번역] random-min-max 해답 번역 3번째줄 번역 #1723

---

1-js/05-data-types/02-number/8-random-min-max/task.md

- random-min-max 과제 문제의 첫번째 줄 번역
- https://ko.javascript.info/number
#1718 
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#1718  random-min-max 과제  번역 첫번째줄

---

1-js/05-data-types/02-number/8-random-min-max/task.md

- random-min-max 과제 문제의 세번째 줄 번역
- https://ko.javascript.info/number
#1719 
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

random-min-max 과제 문제 번역 세번째 줄(#1719)

---

1-js/05-data-types/02-number/8-random-min-max/task.md

- random-min-max 과제 2번째 줄 번역
- # 연관 이슈
(fix #1721)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

#1721 random-min-max 과제 번역 두번째 줄 

---

1-js/05-data-types/12-json/article.md

let json = JSON.stringify(value[, replacer, space]) 오타 수정
JSON.stringify의 문법을 설명하는 부분에서 오타를 발견하여 수정했습니다.
없음.
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[05-data-types/12-json/article.md] 오타 수정

---

1-js/06-advanced-functions/03-closure/1-closure-latest-changes/solution.md
1-js/06-advanced-functions/03-closure/1-closure-latest-changes/task.md
1-js/06-advanced-functions/03-closure/2-closure-variable-access/solution.md
1-js/06-advanced-functions/03-closure/2-closure-variable-access/task.md
1-js/06-advanced-functions/03-closure/7-let-scope/solution.md
1-js/06-advanced-functions/03-closure/7-let-scope/task.md

https://ko.javascript.info/closure#tasks
변수의 유효범위와 클로저 페이지 과제의 미 번역된 3개의 과제를 번역하였습니다. 
없음
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

[신규번역] part1 6.3 함수 심화학습 - 변수의 유효범위와 클로저의 과제

---

2-ui/2-events/03-event-delegation/article.md

내용을 읽다가 "무슨 말이지?"하는 어색한 문장을 발견하여 개선된 번역을 제안합니다.
"이런 단점을 반영하여" 부분은 현재 원문에 없고, 맥락상 이전 내용이 단점으로 언급되는 것이 어색하여 개선된 번역을 제안합니다.
없음
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰

03-event-delegation: '이벤트 위임' 파트의 개선된 번역 제안
