1-js/10-error-handling/2-custom-errors/article.md
Property의 번역어는 `속성`이 아니라 `프로퍼티`로 합의함.
Issue : https://github.com/javascript-tutorial/ko.javascript.info/issues/68
---
안녕하세요? custom error 문서에서 객체의 프로퍼티를 속성으로 번역한 것으로 보여 PR을 작성했습니다. 시간나실때 한번 리뷰 부탁드립니다. 감사합니다.
=> Property 번역어 통일

1-js/99-js-misc/03-currying-partials/article.md
=> [수정완료반영] #110 Curring

1-js/05-data-types/10-destructuring-assignment/article.md
1. (오탈자 수정): 되없습니다 -> 되었습니다 : 오탈자
2. (기타 어색한 표현):  "수반" -> "의미" : mean을 수반하다라는 말보단 의미하다라는 말이 일반적일 것 같습니다.
3. (기타 어색한 표현):  "걸러졌지만" -> "생략되었지만" : 생략으로 바꾸면 skip이란 뜻이 좀 더 명확하게 전달 될 것 같습니다.
4. (미번역): 'only extract title as a variable' -> title만 변수로 뽑아내기
5. (미번역): 'now title="Menu", rest={height: 200, width: 100}' -> 이제 title은 "Menu", rest는 {height: 200, width: 100} 입니다
6. (원문에서 삭제됨):    // 분해의 대상이 아닌 기타 요소 -> 삭제
7. (잘못된 의미): 분해할 -> 반복할, 원문에서의 반복의 의미가 빠져있습니다.
> 원문
```
We can use it with destructuring to loop over keys-and-values of an object:
```
=> 10-destructuring-assignment 리뷰

1-js/02-first-steps/04-variables/article.md, 2-ui/1-document/08-styles-and-classes/article.md
camel case의 번역어가 카멜 케이스, 카멜 표기법으로 혼용되고 있던 것을 카멜 표기법으로 통일함.
````diff
- 카멜 케이스
+ 카멜 표기법
````
close #488 
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
=> camel case 번역어 통일

2-ui/1-document/06-dom-attributes-and-properties/1-get-user-attribute/task.md, 2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/solution.md, 2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/task.md
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
=> [속성과 프로퍼티] 과제 번역

1-js/01-getting-started/1-intro/article.md
번역본에선 위키 링크가 깨져 있어, 원문과 동일하게 수정했습니다.
=> [인트로] 위키 링크 수정

9-regular-expressions/02-regexp-character-classes/article.md
- [V] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
- [V] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
- [V] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
- [V] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [V] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [V] PR 하나엔 번역문 하나만 넣으셨나요?
- [V] 의미 있는 커밋 메시지를 작성하셨나요?
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
9-2. 문자 클래스 번역
=> [문자 클래스] 번역 PR 요청

1-js/09-classes/04-private-protected-properties-methods/article.md
#106 Pull Request 체크리스트
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
> 읽기 전용 프로퍼티 예제
> SyntaxError: missing ) after argument list 에러 발생
>
> private 프로퍼티 예제
> SyntaxError: Unexpected token '('
>
> #waterAmount 생성 예제
> SyntaxError: Private field '#waterAmount' must be declared in an enclosing class
1. 원래 이슈에 있던 3가지의 에러 케이스 중 첫번째 에러만 문제가 있다고 판단하여 첫번째 에러에 대해서만 동작할 수 있게끔 수정하였습니다. 
2. 영어 원문에 에러가 TypeError 가 아니라 Error 로 표기되어 있어 TypeError -> Error 로 수정합니다.
=> [private, protected 프로퍼티와 메서드] 읽기 전용 프로퍼티 예제 SyntaxError 수정

9-regular-expressions/03-regexp-unicode/article.md
96번 줄의 경우 원문은 '-- private use' 였는데 '- private use'의 실수라고 판단해 임의로 수정했는데 문제가 된다면 원문 그대로 다시 변경하겠습니다.
=> [유니코드 클래스] 번역

2-ui/4-forms-controls/1-form-elements/article.md
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
안녕하세요, 처음 번역 PR을 해봅니다. 번역 경험이 거의 없어서 부족한 점이 많지만 튜토리얼 번역판에 정말 도움을 많이 받고 있어서 조금이라도 기여해보고 싶었어요. 리뷰 부탁드립니다..!
(+용어집 편집가능 시트에 backreference와 named collection 두 개의 단어를 추가했는데 제대로 올린 건지 모르겠습니다. 용어집에 올려야 할 용어의 범위가 어디까지인지 궁금해요.)
=> [폼 프로퍼티와 메서드] 본문 번역

7-animation/2-css-animations/2-animate-logo-bezier-css/solution.md
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
=> [CSS 애니메이션] 해답 번역

9-regular-expressions/04-regexp-anchors/1-start-end/solution.md, 9-regular-expressions/04-regexp-anchors/1-start-end/task.md, 9-regular-expressions/04-regexp-anchors/article.md
캐럿 기호 `^`의 경우 삿갓표라는 명칭이 공식 명칭은 아니어서 캐럿 기호로 번역했습니다.
=> [정규식 앵커] 본문 및 과제 번역

5-network/11-websocket/article.md
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
=> [웹소켓] 번역, line25(#883)

5-network/11-websocket/article.md
=> Update Line #20, #67

1-js/10-error-handling/1-try-catch/article.md
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
=> [번역]Part1 10.1 오류 다시 던지기 추가된 영문 번역

2-ui/1-document/11-coordinates/article.md
[번역]Part2 1.11 Coordinates
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
=> [번역]Part2 1.11 Coordinates

1-js/12-generators-iterators/2-async-iterators-generators/article.md
10481e83ef0c4a439bccc0c1f4825245e16f3006 에서 머지하며 원문으로 변경된 번역문을 복구했습니다.
=> [번역] 파트1 - 12.2 덮어쓰기 된 번역 복구

5-network/11-websocket/article.md
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
=> #883 [웹소켓] 번역 - line 98

5-network/11-websocket/article.md
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
=> #883 [웹소켓] 번역 - line 73

5-network/11-websocket/article.md
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
=> #883 [웹소켓] 번역 - line 161

5-network/02-formdata/article.md
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
=> [FormData] 번역 - line178(#1232)

2-ui/2-events/03-event-delegation/4-behavior-tooltip/solution.view/index.html, 2-ui/2-events/03-event-delegation/4-behavior-tooltip/source.view/index.html, 2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
=> [이벤트 위임] 과제4 번역(#1313)

1-js/06-advanced-functions/02-rest-parameters-spread/article.md
Summary:
6.2 나머지 매개변수와 전개 문법 챕터 중 오타 두 가지를 수정한 PR합니다: 
[6.2 나머지 매개변수와 전개 문법 중 <arguments 객체> 섹션](https://ko.javascript.info/rest-parameters-spread#ref-4859)
1. arguemnts -> arguments
같은 6.2 챕터 중 [배열과 객체의 복사본 만들기](https://ko.javascript.info/rest-parameters-spread#ref-4860)
2. Object.assign() 참조에 의한 객체 복사 챕터에서 Object.assign()을 사용해 객체를 복사한 예시를 떠올려봅시다. -> 참조에 의한 객체 복사 챕터에서 Object.assign()을 사용해 객체를 복사한 예시를 떠올려봅시다.
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
=> fix: 6.2 나머지 매개변수와 전개 문법 중 <arguments 객체> 오타 (#1493)

2-ui/1-document/05-basic-dom-node-properties/2-tree-info/solution.md
Part2 1.5 주요 노드 프로퍼티 첫 번째 과제(후손 노드 개수 세기) 해답 부분 번역을 진행하였습니다.
| 번역 전 | 번역 후 |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/78653426/187068060-d5427594-772b-48e3-886b-09bccaae421b.png) |![image](https://user-images.githubusercontent.com/78653426/187068007-ca0d033f-79fa-46d6-a205-6d6408a927af.png) |
[이슈 #1525](https://github.com/javascript-tutorial/ko.javascript.info/issues/1525)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
=> [신규 번역] Part2 1.5 주요 노드 프로퍼티 과제1 해답 (#1525)

5-network/11-websocket/article.md
웹소켓 238번째 줄 번역
(fix #일이삼)
#1606 
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
=> [웹소켓] 번역 - line238 (#1606)

1-js/11-async/02-promise-basics/article.md
[프로미스](https://ko.javascript.info/promise-basics)
상단 코드와 하단 다이어그램에는 모두 `resolve("완료")` 라고 되어있지만, 설명문에는 `resolve("done")` 이라고 되어있습니다.
(fix #1683)
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
=> [오타수정] Part 1.11.2 Promise (#1683)

1-js/05-data-types/02-number/8-random-min-max/solution.md
random-min-max solution 번역 5번째 줄
#1717
- 예시
- [프락시] 번역
- [프락시] 과제 번역
- [주석] 2차 리뷰
=> #1717 random-min-max solution 번역 5번째 줄
